* -----------------------------------------------------
* XLS2GMS 2.8      24.3.3 r48116 Released Sep 19, 2014 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Users\mchoobin\Dropbox\Future projects\CES\data\New data 3 Aug\Input_data.xls
* Sheet:       ExtApt
* Range:       $I$54:$O$74
* -----------------------------------------------------     
1    0      
2    0      
3    0         
4    0       
5    0        
6    0     
7    0      
8    0  
9    2.5 
10   2.5 
11   3
12   3
13   3
14   2.8
15   2.8
16   3.5
17   3.5
18   4
19   4
20   3.5  
* -----------------------------------------------------
