* -----------------------------------------------------
* XLS2GMS 2.8      24.3.3 r48116 Released Sep 19, 2014 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Users\mchoobin\Dropbox\Future projects\CES\data\New data 3 Aug\Input_data.xls
* Sheet:       ExtApt
* Range:       $I$54:$O$74
* -----------------------------------------------------     
1    0      
2    0      
3    0         
4    0       
5    0        
6    0         
7    0          
8    0      
9    0.1     
10   0.1    
11   0.2   
12   0.2   
13   0.2   
14   0.16
15   0.16
16   0.24
17   0.24
18   0.3
19   0.3
20   0.24  
* -----------------------------------------------------
